"""classificacao dos documentos de caso

Revision ID: 8d06fc8d27e7
Revises: 2c6b722fb2df
Create Date: 2026-09-07 13:58:20.250245

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d06fc8d27e7"
down_revision: Union[str, Sequence[str], None] = "2c6b722fb2df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "caso_documentos",
        sa.Column("tipo_documento", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "caso_documentos", sa.Column("vinculo_ato", sa.String(length=30), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("caso_documentos", "vinculo_ato")
    op.drop_column("caso_documentos", "tipo_documento")
    # ### end Alembic commands ###
