"""adiciona artigo aos chunks

Revision ID: 8d95f6987e80
Revises: b55821e1cf5d
Create Date: 2026-09-03 16:50:09.132539

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d95f6987e80"
down_revision: Union[str, Sequence[str], None] = "b55821e1cf5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documento_chunks", sa.Column("artigo", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documento_chunks", "artigo")
    # ### end Alembic commands ###
