"""estrutura inicial da analise

Revision ID: e7c5ec4d3cdf
Revises: c38e920f4a61
Create Date: 2026-09-07 12:37:37.773526

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7c5ec4d3cdf"
down_revision: Union[str, Sequence[str], None] = "c38e920f4a61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "casos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("titulo", sa.String(length=200), nullable=False),
        sa.Column("identificacao", sa.String(length=100), nullable=True),
        sa.Column("tipo_ato", sa.String(length=100), nullable=True),
        sa.Column("descricao", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("criado_por", sa.Uuid(), nullable=False),
        sa.Column("responsavel_id", sa.Uuid(), nullable=True),
        sa.Column("encerrado_em", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["criado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["responsavel_id"], ["usuarios.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_casos_criado_por_created_at",
        "casos",
        ["criado_por", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_casos_status_updated_at", "casos", ["status", "updated_at"], unique=False
    )
    op.create_table(
        "caso_documentos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("caso_id", sa.Uuid(), nullable=False),
        sa.Column("nome_arquivo", sa.String(length=255), nullable=False),
        sa.Column("caminho_arquivo", sa.String(length=500), nullable=False),
        sa.Column("hash_arquivo", sa.String(length=64), nullable=True),
        sa.Column("mime_type", sa.String(length=150), nullable=True),
        sa.Column("tamanho_bytes", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("erro_processamento", sa.Text(), nullable=True),
        sa.Column("total_paginas", sa.Integer(), nullable=False),
        sa.Column("situacao_extracao", sa.String(length=30), nullable=False),
        sa.Column("diagnostico_extracao", sa.JSON(), nullable=True),
        sa.Column("criado_por", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["caso_id"], ["casos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["criado_por"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "caso_id", "hash_arquivo", name="uq_caso_documentos_caso_hash"
        ),
    )
    op.create_index(
        "ix_caso_documentos_caso_status",
        "caso_documentos",
        ["caso_id", "status"],
        unique=False,
    )
    op.create_table(
        "caso_fatos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("caso_id", sa.Uuid(), nullable=False),
        sa.Column("caso_documento_id", sa.Uuid(), nullable=True),
        sa.Column("campo", sa.String(length=150), nullable=False),
        sa.Column("categoria", sa.String(length=80), nullable=True),
        sa.Column("locus", sa.String(length=30), nullable=True),
        sa.Column("valor_original", sa.JSON(), nullable=True),
        sa.Column("valor_atual", sa.JSON(), nullable=True),
        sa.Column("proveniencia", sa.String(length=30), nullable=False),
        sa.Column("estado_evidencia", sa.String(length=30), nullable=False),
        sa.Column("estado_conferencia", sa.String(length=20), nullable=False),
        sa.Column("pagina", sa.Integer(), nullable=True),
        sa.Column("localizacao", sa.String(length=200), nullable=True),
        sa.Column("trecho_fonte", sa.Text(), nullable=True),
        sa.Column("metodo_extracao", sa.String(length=30), nullable=True),
        sa.Column("contexto", sa.JSON(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("registrado_por", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "estado_conferencia IN ('PENDENTE', 'CONFIRMADO', 'CORRIGIDO')",
            name="ck_caso_fatos_estado_conferencia",
        ),
        sa.CheckConstraint(
            "estado_evidencia IN ('ENCONTRADO', 'AUSENTE', 'INCERTO', 'CONFLITANTE')",
            name="ck_caso_fatos_estado_evidencia",
        ),
        sa.ForeignKeyConstraint(
            ["caso_documento_id"], ["caso_documentos.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["caso_id"], ["casos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["registrado_por"], ["usuarios.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_caso_fatos_caso_estado",
        "caso_fatos",
        ["caso_id", "estado_evidencia", "estado_conferencia"],
        unique=False,
    )
    op.create_index(
        "ix_caso_fatos_documento", "caso_fatos", ["caso_documento_id"], unique=False
    )
    op.create_table(
        "caso_conferencias",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("caso_id", sa.Uuid(), nullable=False),
        sa.Column("fato_id", sa.Uuid(), nullable=False),
        sa.Column("usuario_id", sa.Uuid(), nullable=True),
        sa.Column("acao", sa.String(length=20), nullable=False),
        sa.Column("valor_anterior", sa.JSON(), nullable=True),
        sa.Column("valor_novo", sa.JSON(), nullable=True),
        sa.Column("observacao", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "acao IN ('CONFIRMAR', 'CORRIGIR', 'REABRIR')",
            name="ck_caso_conferencias_acao",
        ),
        sa.ForeignKeyConstraint(["caso_id"], ["casos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["fato_id"], ["caso_fatos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuarios.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_caso_conferencias_caso_created_at",
        "caso_conferencias",
        ["caso_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_caso_conferencias_fato_created_at",
        "caso_conferencias",
        ["fato_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_caso_conferencias_fato_created_at", table_name="caso_conferencias"
    )
    op.drop_index(
        "ix_caso_conferencias_caso_created_at", table_name="caso_conferencias"
    )
    op.drop_table("caso_conferencias")
    op.drop_index("ix_caso_fatos_documento", table_name="caso_fatos")
    op.drop_index("ix_caso_fatos_caso_estado", table_name="caso_fatos")
    op.drop_table("caso_fatos")
    op.drop_index("ix_caso_documentos_caso_status", table_name="caso_documentos")
    op.drop_table("caso_documentos")
    op.drop_index("ix_casos_status_updated_at", table_name="casos")
    op.drop_index("ix_casos_criado_por_created_at", table_name="casos")
    op.drop_table("casos")
    # ### end Alembic commands ###
